### ISSUE TITLE
运行后不显示界面 什么情况？

### ISSUE THREAD

**Issue by kanxue2002** [prototypecodegenerator/lanhu#1]

**Comment by songxing10000** [comment]
1

**Comment by josercc** [comment]
@kanxue2002 @songxing10000 运行 2.0.0分支代码

**Comment by josercc** [comment]
2.0.0用SwiftUI重写了 解析了数据 还不知道后面怎么做

**Comment by songxing10000** [comment]
@josercc 用的最新的代码

**Comment by josercc** [comment]
@songxing10000 我的用的语言比较新 你Xcode版本 macOS版本多少

**Comment by songxing10000** [comment]
@josercc 刚下载了你新的提交可以正常运行出界面了

**Comment by josercc** [comment]
> @josercc 刚下载了你新的提交可以正常运行出界面了

我没有新的提交 只是变更了默认的分支

**Comment by songxing10000** [comment]
但是点登录没反应奇怪了
![image](https://user-images.githubusercontent.com/10040131/154431692-41d35596-9abb-430b-99b6-ca6b302f29b1.png)

**Comment by josercc** [comment]
> 但是点登录没反应奇怪了
> ![image](https://user-images.githubusercontent.com/10040131/154431692-41d35596-9abb-430b-99b6-ca6b302f29b1.png)

这个就是浏览器打开蓝湖走蓝湖登录的呀

**Comment by songxing10000** [comment]
是啊，但是点了没反应了。难道要打开系统的浏览器或者 chrome，然后app会自动同步这个登录状态吗

**Comment by josercc** [comment]
> 是啊，但是点了没反应了。难道要打开系统的浏览器或者 chrome，然后app会自动同步这个登录状态吗

我试一下 不会同步的 不同浏览器

**Comment by josercc** [comment]
> 是啊，但是点了没反应了。难道要打开系统的浏览器或者 chrome，然后app会自动同步这个登录状态吗

我试了一下 是可以登录的 我用的微信扫码登录
